### ISSUE TITLE
stackoverflow

### ISSUE THREAD

**Issue by jadcoding** [muhammadikram0192/Demo#2]
hello

**Comment by muhammadikram0192** [comment]
I am looking at the plugin called "masonry". I will look into this

**Comment by jadcoding** [comment]
ok  plz try to add this in the head  https://getbootstrap.com/docs/3.3/getting-started/ the two bootstrap cdn style links

**Comment by jadcoding** [comment]
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

**Comment by jadcoding** [comment]
![Screenshot_2019-03-26_19-08-39](https://user-images.githubusercontent.com/34236432/55018016-a9298680-4ffa-11e9-9cb1-0581aca099a6.png)
